kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: freshairweb/refresh-website
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD